# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Using a Python image with uv pre-installed
FROM python:3.13-slim AS uv

# Setting the working directory
WORKDIR /app

# Copying the necessary files
COPY pyproject.toml uv.lock ./
RUN pip install --no-cache-dir uv && uv sync --frozen --no-dev --no-editable

# Copying the rest of the application files
COPY . .

# Upgrading pip and install Python dependencies
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    rm requirements.txt

# Installing Node.js and npm required by `mcp dev`
RUN apt-get update && apt-get install -y nodejs npm && rm -rf /var/lib/apt/lists/*

# Exposing port 8080 for the application
EXPOSE 8080

ENTRYPOINT ["python", "src/server.py"]
